### ISSUE TITLE
On hover text should be visible properly like in original website

### ISSUE THREAD

**Issue by nitansh11** [sandeshjadhav5/careless-tiger-9091#53]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/8274883/212794612-17eefb4a-cbe5-4e22-950c-c6db06d8e53f.png">

**Comment by nitansh11** [comment]
Also when click on shop button nothing happens. Can redirect to products page.

**Comment by sandeshjadhav5** [comment]
resolved this issue 
on hover, text will be black and the background will be lightblue
